source 'https://github.com/CocoaPods/Specs.git'

target 'DZVideoPlayerViewController_Example', :exclusive => true do
  pod "DZVideoPlayerViewController", :path => "../"
end

target 'DZVideoPlayerViewController_Tests', :exclusive => true do
  pod "DZVideoPlayerViewController", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
